# Generated by Django 2.2.24 on 2023-07-19 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_auto_20230719_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(max_length=20, verbose_name='Телеграм id')),
                ('name', models.CharField(default='Дорогой Гость', max_length=30, verbose_name='Имя')),
                ('address', models.CharField(blank=True, max_length=80, null=True, verbose_name='Адрес')),
                ('consent_to_pdProc', models.BooleanField(default=False, verbose_name='Согласие на обработку ПД')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('short_delivery_time', models.BooleanField(default=False, verbose_name='Сокращенное время доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cake', verbose_name='Торт')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='datacenter.Client', verbose_name='Клиент')),
            ],
        ),
    ]
