# Generated by Django 2.2.24 on 2023-07-18 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=False, verbose_name='Есть в наличии')),
                ('title', models.CharField(max_length=20, verbose_name='Название ягод')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=False, verbose_name='Есть в наличии')),
                ('title', models.CharField(max_length=20, verbose_name='Название декора')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=False, verbose_name='Есть в наличии')),
                ('title', models.CharField(max_length=20, verbose_name='Название формы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=False, verbose_name='Есть в наличии')),
                ('title', models.CharField(max_length=20, verbose_name='Название топпинга')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_original', models.BooleanField(default=False, verbose_name='Оригинальный')),
                ('title', models.CharField(max_length=50, verbose_name='Название торта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('levels', models.IntegerField(choices=[(1, '1 уровень'), (2, '2 уровня'), (3, '3 уровня')], default=1, verbose_name='Количество уровней')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Надпись на торте')),
                ('berries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Berries', verbose_name='Ягоды')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Shape', verbose_name='Форма')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Topping', verbose_name='Топпинг')),
            ],
        ),
    ]
