# Generated by Django 2.2.24 on 2023-07-18 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=False, verbose_name='Есть в наличии')),
                ('title', models.IntegerField(choices=[(1, '1 уровень'), (2, '2 уровня'), (3, '3 уровня')], default=1, unique=True, verbose_name='Количество уровней')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cake',
            name='levels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.Levels', verbose_name='Уровни'),
        ),
    ]
