# Generated by Django 2.2.24 on 2023-07-19 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_client_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Скидка')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='creation',
            new_name='order_dt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='short_delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='complaint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Complaint'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.PromoCode', verbose_name='Промокод'),
        ),
    ]
