# Generated by Django 2.2.24 on 2023-07-20 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20230720_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='levels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.Levels', verbose_name='Уровни'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.Shape', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название торта'),
        ),
    ]
