# Generated by Django 2.2.24 on 2023-07-20 23:32

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20230720_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('shorten_link', models.CharField(default=bot.models.Link.__get_shorten_link, max_length=30, verbose_name='Сокращенная ссылка')),
            ],
        ),
    ]
